Add authorization to Bifrost aggregated data - PLAT-202
buildlyio/buildly-core pull request #10
Opened 2019-02-01 13:52 UTC by ralfzen

## Purpose

When we need to aggregate data from Bifrost, the application accesses the database directly, in order to retrieve the needed data. We need to make sure the user who is requesting the data is allowed to see it, in other words, we need to validate user permissions.

Related: https://humanitec.atlassian.net/browse/PLAT-202

2019-02-04 13:14 UTC, jefmoura requested changes

2019-02-04 13:14 UTC, jefmoura commented on gateway/utils.py
> +    :param obj:
Can you describe the parameters?

2019-02-04 13:14 UTC, jefmoura commented on gateway/tests/test_utils.py
> +class UtilsValidateBifrostObjectAccessTest(TestCase):
It'd be good to have a test covering the `KeyError`

2019-02-04 13:14 UTC, jefmoura commented on gateway/tests/test_utils.py
> +
I think we should have a test for default DRF_Permission_setting

2019-02-04 13:14 UTC, jefmoura commented on gateway/utils.py
> +        viewset = MODEL_VIEWSETS_DICT[model](action=action)
You don't need to pass the action to create a view set obj.

2019-02-04 13:14 UTC, jefmoura commented on gateway/utils.py
> +    permissions = getattr(viewset, 'permission_classes',
It's better to use the function `get_permissions` instead

2019-02-04 13:14 UTC, jefmoura commented on gateway/utils.py
> +        if not permission_class().has_object_permission(request, viewset, obj):
I think we could just use the function `check_object_permissions` from the view instead of loading the permissions classes and looping over it. What do you think?

2019-02-05 15:42 UTC, jefmoura commented
It needs rebase @ralfzen

2019-02-06 14:40 UTC, docktorrr approved these changes

2019-02-06 14:44 UTC, ralfzen commented
Thanks @jefmoura

2019-02-06 14:52 UTC, jefmoura approved these changes

2019-02-06 14:52 UTC, merged