Remove unused PrimJSONEncoder - PLAT-243
buildlyio/buildly-core pull request #13
Opened 2019-02-05 16:43 UTC by ralfzen

Fixes the bug with unhandled Primitives. Actually the `PrimJSONEncoder` - class was never called from `json.dumps()`:
```
def dumps(obj, *, skipkeys=False, ensure_ascii=True, check_circular=True,
        allow_nan=True, cls=None, indent=None, separators=None,
        default=None, sort_keys=False, **kw):
    if (not skipkeys and ensure_ascii and
        check_circular and allow_nan and
        cls is None and indent is None and separators is None and
        default is None and not sort_keys and not kw):
        return _default_encoder.encode(obj)
    if cls is None:
        cls = JSONEncoder
    return cls(
        skipkeys=skipkeys, ensure_ascii=ensure_ascii,
        check_circular=check_circular, allow_nan=allow_nan, indent=indent,
        separators=separators, default=default, sort_keys=sort_keys,
        **kw).encode(obj)
```

2019-02-05 17:26 UTC, jefmoura requested changes

2019-02-05 17:26 UTC, jefmoura commented on gateway/utils.py
> +def obj_to_json_handler(obj):
- Why are you using the same function?
- Why don't you create a JSONEncoder class?

2019-02-05 17:26 UTC, jefmoura commented on gateway/utils.py
> +    # for handling pyswagger.primitives
Magic methods are recommended to not be used directly, so cast the UUID directly instead

2019-02-05 17:26 UTC, jefmoura commented on gateway/utils.py
> +    return json.dumps(obj, default=obj_to_json_handler)
- Why do we have this `json_dumps` function?
- Do we really need it?

2019-02-05 17:30 UTC, jefmoura commented
Where are the tests?

2019-02-06 15:23 UTC, docktorrr approved these changes

2019-02-06 15:25 UTC, ybekdemir approved these changes

2019-02-06 15:26 UTC, jefmoura approved these changes

2019-02-06 15:26 UTC, merged