Data mesh ready for Time-Tracking
buildlyio/buildly-core pull request #21
Opened 2019-02-08 14:24 UTC by ralfzen

With these changes, the following relationships are working:
{"time-event": {"core_user_uuid": "bifrost.CoreUser", "appointment_uuid": "crm.Appointment"}}

It is merge-ready and usable.

2019-02-11 10:54 UTC, jefmoura commented on gateway/views.py
> +                        pk = str(pk)  # pk is a Primitive and must convert
I'd say that it's better to convert it when we're generating the extension map instead of checking it here.

2019-02-11 10:54 UTC, jefmoura commented on gateway/views.py
> +            try:  # support lookup by id OR uuid
If you add the change mentioned above, we won't have this problem. We have this issue because of the extension map.

2019-02-11 10:54 UTC, jefmoura commented on workflow/views.py
> +            lookup_field = 'id'
Checking if it's an integer or UUID, it's a better practice then using a try-catch block to control flow.

2019-02-11 21:18 UTC, ralfzen commented on gateway/views.py
> +                        pk = str(pk)  # pk is a Primitive and must convert
Good point! Done. :)

2019-02-12 09:38 UTC, jefmoura requested changes
Where are the test to check if `lookup_field='core_user_uuid'` is working?

2019-02-12 09:38 UTC, jefmoura commented on gateway/views.py
> +                    pk_name = extend_model['relationship_key']
- You need to check if the class has such attribute, otherwise, it'll raise an error.
- Please, add a test for this scenario as well.

2019-02-12 09:38 UTC, jefmoura commented on gateway/views.py
> +                'pk': str(data[k]) if hasattr(data[k], 'to_json') else data[k],
I think it's easier to cast it to string all the time. I don't think it'll have a bad effect. Could you try it?

2019-02-12 09:38 UTC, jefmoura commented on workflow/models.py
> +    workflowlevel1_uuid = models.CharField(max_length=255, editable=False, verbose_name='WorkflowLevel1 UUID', default=uuid.uuid4, unique=True)
Change it to UUIDField

2019-02-12 09:38 UTC, jefmoura commented on workflow/models.py
> +    workflowlevel2_uuid = models.CharField(max_length=255, editable=False, verbose_name='WorkflowLevel2 UUID', default=uuid.uuid4, unique=True, blank=True, help_text="Unique ID")
Change it to UUIDField so

2019-02-12 12:26 UTC, ralfzen commented on gateway/views.py
> +                    pk_name = extend_model['relationship_key']
done

2019-02-12 12:27 UTC, ralfzen commented on gateway/views.py
> +                'pk': str(data[k]) if hasattr(data[k], 'to_json') else data[k],
works also

2019-02-12 12:28 UTC, ralfzen commented on workflow/models.py
> +    workflowlevel1_uuid = models.CharField(max_length=255, editable=False, verbose_name='WorkflowLevel1 UUID', default=uuid.uuid4, unique=True)
The change to UUIDField throws:
`django.db.utils.ProgrammingError: operator class "varchar_pattern_ops" does not accept data type uuid`
I would like to postpone this change because of time reasons.

2019-02-12 12:28 UTC, ralfzen commented on workflow/models.py
> +    workflowlevel2_uuid = models.CharField(max_length=255, editable=False, verbose_name='WorkflowLevel2 UUID', default=uuid.uuid4, unique=True, blank=True, help_text="Unique ID")
same here

2019-02-12 12:40 UTC, docktorrr requested changes
Refactored tests for wf1 and wf2 are already in master, so the branch is out-of-date. Could you rebase and fix conflicts if they appears (as you changed the field names, so it's needed to change tests as well).

2019-02-12 12:43 UTC, jefmoura commented on workflow/models.py
> +    workflowlevel1_uuid = models.CharField(max_length=255, editable=False, verbose_name='WorkflowLevel1 UUID', default=uuid.uuid4, unique=True)
The issue is that you still have an old index on the uuid field that clashes with the new type.

2019-02-12 12:52 UTC, jefmoura requested changes
You need to rebase.

2019-02-12 12:52 UTC, jefmoura commented on gateway/views.py
> +            key = k.split('.')
Why are you splitting the key? It doesn't match with the definition in the documentation.
https://github.com/Humanitec/docs-site/blob/master/hugo/content/walhall/bifrost/internal.md#data-model-relationships

2019-02-12 12:52 UTC, jefmoura commented on gateway/views.py
> +                    pk_name = extend_model['lookup_field']
It's Bifrost and we have control over it, so we just need to use `uuid` all the time and make sure that all the models have a UUID.

2019-02-12 12:52 UTC, jefmoura commented on gateway/views.py
> +                'expand_field': expand_field,
As I explained above about having UUID in all Bifrost models, we don't this extra field and if-else statement logic.

2019-02-12 13:23 UTC, ralfzen commented on gateway/views.py
> +            key = k.split('.')
I've added these two features for two reasons:
1. The lookup_field enables us to also lookup with different keys.
2. The expand_field lets us define, where the new data can be put into. It was ugly to have the expanded data in the field `uuid`.

I think that is a first step, to get also other endpoints running in the future.

2019-02-12 13:24 UTC, ralfzen commented on gateway/views.py
> +                    pk_name = extend_model['lookup_field']
I won't manage it today, to change all fields to uuid and adapt all tests. That will break our user-tests.

2019-02-12 13:47 UTC, ralfzen commented on gateway/views.py
> +                'expand_field': expand_field,
It makes the Data Mesh more explicit and gives us more control how it should work in the future.
In my eyes a more explicit structure would make the work the Data Mesh easier:
```
"relationships": {
            "time-event": {
                "core_user_uuid": "bifrost.CoreUser",
                "appointment_uuid": "crm.Appointment"
            }
        },
->
"relationships": {
            "time-event": [{
                "related_field": "core_user_uuid",
		"lookup_field": "uuid",  # can also be default
		"lookup_logic_module": "bifrost",
		"lookup_endpoint": "coreuser"
		}, {
                "related_field": "appointment_uuid",
		"lookup_field": "uuid",  # can also be default
		"lookup_logic_module": "crm",
		"lookup_endpoint": "appointment"
            }]
        },
```
That way can also define names for the relationships for selecting which relationship should be followed in deeper depths.

2019-02-12 14:00 UTC, ralfzen commented on gateway/views.py
> +            key = k.split('.')
At least it conforms to the definition in the documentation because it keeps its functionality but adds 2 more extras to keep the kupfer deadline.

2019-02-12 14:25 UTC, jefmoura commented on gateway/views.py
> +            key = k.split('.')
- Data mesh should do joins by PKs, like databases, and if a user wants to do lookups with different keys, they should filter instead.
- The `k.split('.')` doesn't make sense yet. There's no key with `.`, so it doesn't match with the definition in the documentation.

2019-02-12 14:38 UTC, jefmoura commented on gateway/views.py
> +                'expand_field': expand_field,
- This change would make the work with Data mesh easier but we need to change more things that you've already changed and update the documentation.
- It looks pretty much the same for me, you just break it into key-value pairs.
- Why do we need this `lookup_field` if the relationship should always be via PK - FK?

2019-02-12 14:59 UTC, ralfzen commented on gateway/views.py
> +                'expand_field': expand_field,
- Yes, with these key-value pairs we can extend the dictionary with more keys and have it more explicit.
- I needed the lookup-field, because I wanted to retrieve the CoreUser through `core_user_uuid` not `uuid`. Now that we have aligned on using `uuid` everywhere, I can remove this, but I think it makes the Data Mesh more flexible. The data structure shouldn't adapt to the Data Mesh. The Data Mesh should adapt.
- Yes, I think the current implementation is working well and I like it, the more I get used to it, but it has its shortcomings:
  - We can not define if we want to replace the field, or if we want to insert the meshed data into a new field. 
  - At the moment we would follow all relationships if we increase the depth. But if we add relationship-names, we could implement a `?depth=2&follow=(rel_name1,rel_name2,...)` to follow only certain relations.

2019-02-12 15:24 UTC, jefmoura commented on gateway/views.py
> +                'expand_field': expand_field,
- I think you didn't get what I said about the `lookup-field`. When you send a request to a service it's like this `/<service>/<model>/<id>/`, e.g, `/crm/appointment/123/`; so the `lookup-field` can be anything that it won't affect the way that the data mesh works because it's using the service API. The data mesh isn't forcing anyone to adapt, it may be forcing the developers to implement an API in the right way.
- Our data structure should change because we're implementing it and accessing the database directly instead of sending a request
- I don't know why you're some much into having depth in the current implementation if it's not even implemented and we've already talked about updating it in the **FUTURE**.

2019-02-12 15:55 UTC, ralfzen commented on gateway/views.py
> +                'expand_field': expand_field,
- We have margin case with the bifrost-lookups: 
https://github.com/Humanitec/bifrost/blob/master/gateway/views.py#L205
CoreUser is part of Bifrost. That is where I ran into problems.
- Yes, we have a refactoring sprint, but the Kupfer Team also has to bring up new (old) features at the same time. That is, why I am trying to find a way to get both handled.
- Of course the depth is not part of our current scope, but it will be needed in one of the next sprints.

2019-02-12 16:36 UTC, ralfzen commented on gateway/views.py
> +                'expand_field': expand_field,
In https://github.com/Humanitec/bifrost/blob/master/gateway/views.py#L208 we have
`pk_name = cls._meta.pk.attname` what brings `{'id': <something_we_do_not_exactly_know>}` what brings `ValueError at /timetracking/time-event/
invalid literal for int() with base 10: 'None'`
My first approach was to insert the `relationship_key`. That worked but is also static and does not fit to all models. My next gues would be to use always `uuid`, but that brings in case of CoreUser: `Cannot resolve keyword 'uuid' into field. Choices are: auth_approving, contact_info, core_user_uuid, create_date, edit_date, id, organization, organization_id, privacy_disclaimer_accepted, title, user, user_id, workflowlevel1`

2019-02-12 16:43 UTC, jefmoura commented on gateway/views.py
> +                'expand_field': expand_field,
1. Regarding your first comment we already talked about it here https://github.com/Humanitec/bifrost/pull/21#discussion_r255938057
2. Regarding your second comment we also talked about it here https://github.com/Humanitec/bifrost/pull/21#discussion_r255406821

2019-02-12 16:57 UTC, ralfzen commented on gateway/views.py
> +                'expand_field': expand_field,
Ok, I'll change the related models to UUID and set it back to the relationship_key, what will cost me nearly another day.

2019-02-13 08:12 UTC, glind commented
These conversations are getting a bit out of hand and don't seem to be getting us any closer to resolving the issue.  We are blocking front-end developers at the moment.  Let's resolve this morning and move on please.

2019-02-18 11:20 UTC, ralfzen commented
This issue is resolved and can be closed.

2019-02-18 11:20 UTC, closed without merging