Modified Swagger URL retrieval to handle exceptions for unavailable endpoint
buildlyio/buildly-core pull request #219
Opened 2019-09-26 22:20 UTC by msradam

## Purpose
#198, creates the expected behavior for adding a logic module with an unavailable URL.

## Approach
Adds a timeout to the GET request for retrieving the Swagger documentation for the service, and if there is no response within the timeout or the connection fails, it will raise a TimeoutError or ConnectionError to the Swagger Aggregator, which will log the response accordingly. This allows for the Buildly API and services API documentation to be visible on the Swagger documentation, while unavailable services do not show up.

### Further Info
_@jefmoura_
May need to revise timeout duration. 
Prior to this fix, the exception message raised from `get_swagger_from_url()` was not logged to the console, this is fixed now.

2019-09-27 09:26 UTC, jefmoura commented
This PR will fix the Travis issue.
https://github.com/buildlyio/buildly-core/pull/220

2019-09-30 18:37 UTC, jefmoura requested changes

2019-09-30 18:37 UTC, jefmoura commented on gateway/tests/test_utils.py
> +        mock_request_get.side_effect = [ConnectionError, TimeoutError]
The function `requests.get` is called only once, so only the first exception will be raised. Therefore, we need to implement two tests to test the different exceptions.
https://docs.python.org/3/library/unittest.mock-examples.html#side-effect-functions-and-iterables

2019-10-01 14:47 UTC, msradam commented on gateway/tests/test_utils.py
> +        mock_request_get.side_effect = [ConnectionError, TimeoutError]
Added a new commit that includes separate tests for timeout and connection errors, using pytest instead of the Django TestCase class.

2019-10-02 19:40 UTC, jefmoura approved these changes

2019-10-02 19:40 UTC, merged