Add registration process
buildlyio/buildly-core pull request #3
Opened 2019-01-31 17:15 UTC by docktorrr

## Purpose
Add registration process and update invitation process in Bifrost

## Approach
- Invitation model is created which stores an invitation token
- Invitation process was reworked
- UserViewSet was removed as it's not used
- CoreUser Serializer was updated
- Permission for updating CoreUser was set to Org Admin
- Email backend in settings

2019-02-01 08:16 UTC, jefmoura requested changes

2019-02-01 08:16 UTC, jefmoura commented on workflow/models.py
> +        return u'{}'.format(self.name)
Unicode is default in Django 2.0, so you don't need to do that. Just `str(self.name)` will work.

2019-02-01 08:16 UTC, jefmoura commented on workflow/models.py
> +        return u'{}'.format(self.name)
Unicode is default in Django 2.0, so you don't need to do that. Just `str(self.name)` will work.

2019-02-01 08:16 UTC, jefmoura commented on workflow/views.py
> +    @staticmethod
Why is it a static method?

2019-02-01 08:16 UTC, jefmoura commented on workflow/views.py
> +            reply_to=[]  # TODO: define reply-to email for org
Usually, we don't have a reply to for the invitation. I don't know why we have in the old implementation.

2019-02-01 08:16 UTC, jefmoura commented on workflow/models.py
> +class Invitation(models.Model):
Do we really need a new model just to invite users?

2019-02-01 08:16 UTC, jefmoura commented on workflow/models.py
> +    token = models.CharField(max_length=255, verbose_name='Token',
UUID isn't a token.

2019-02-01 08:16 UTC, jefmoura commented on workflow/serializers.py
> +    @staticmethod
Why is it a static method?

2019-02-01 08:16 UTC, jefmoura commented on workflow/views.py
> +                    reg_location.format(invitation.token)
For how long this token is valid?

2019-02-01 08:17 UTC, ralfzen submitted a review, later dismissed

2019-02-01 08:17 UTC, ralfzen commented on workflow/tests/test_workflowteamview.py
> +        tolauser_url = reverse('coreuser-detail',
let's get rid of tolauser and rename this to coreuser_url

2019-02-04 10:02 UTC, rafa-munoz requested changes

2019-02-04 10:02 UTC, rafa-munoz commented on workflow/views.py
> +                print(token)
Remove the print

2019-02-04 10:07 UTC, ybekdemir requested changes

2019-02-04 10:07 UTC, ybekdemir commented on workflow/views.py
> +            'exp': datetime.datetime.utcnow() + datetime.timedelta(days=30)
I am not sure but for the other projects, invitation link should be valid for 24 hours. I could not find clear definition in the ticket.

2019-02-04 10:09 UTC, ybekdemir submitted a review, later dismissed

2019-02-04 10:09 UTC, ybekdemir commented on workflow/tests/test_workflowteamview.py
> +        tolauser_url = reverse('coreuser-detail',
Again, no tolauser anymore. We should change this with coreuser.

2019-02-04 10:09 UTC, ybekdemir commented on workflow/tests/test_workflowteamview.py
> +        tolauser_url = reverse('coreuser-detail',
Again, tolauser_url.

2019-02-04 10:09 UTC, ybekdemir commented on workflow/tests/test_workflowteamview.py
> +        tolauser_url = reverse('coreuser-detail',
Again, tolauser_url.

2019-02-04 10:14 UTC, docktorrr commented on workflow/tests/test_workflowteamview.py
> +        tolauser_url = reverse('coreuser-detail',
but that's what i did - replaced toladata with coreuser

2019-02-04 10:19 UTC, rafa-munoz commented on workflow/views.py
> +    @staticmethod
I cannot see now the next line because it is outdated, but as a general rule it's good if the function does not use any of the instance's parameters to make the method static

2019-02-04 10:20 UTC, rafa-munoz commented on workflow/tests/test_workflowteamview.py
> +        tolauser_url = reverse('coreuser-detail',
I guess he meant `tolauser_url`.

2019-02-04 10:21 UTC, ybekdemir commented on workflow/tests/test_workflowteamview.py
> +        tolauser_url = reverse('coreuser-detail',
Yes, it was ```tolauser_url``` .  Sorry for the misunderstanding.

2019-02-04 10:24 UTC, docktorrr commented on workflow/tests/test_workflowteamview.py
> +        tolauser_url = reverse('coreuser-detail',
Ah, yes, we'll do it during refactoring, I replaced it here to avoid errors.

2019-02-04 10:27 UTC, docktorrr commented on workflow/views.py
> +    @staticmethod
@Menda It didn't use instance of course. But anyway I removed it

2019-02-04 10:38 UTC, docktorrr commented on workflow/views.py
> +                print(token)
done

2019-02-04 10:39 UTC, docktorrr commented on workflow/views.py
> +            'exp': datetime.datetime.utcnow() + datetime.timedelta(days=30)
I set it to 24h and put it in settings file

2019-02-04 10:39 UTC, docktorrr commented on workflow/tests/test_workflowteamview.py
> +        tolauser_url = reverse('coreuser-detail',
Ok, already done :)

2019-02-04 13:51 UTC, rafa-munoz submitted a review, later dismissed

2019-02-04 13:53 UTC, rafa-munoz reviewed
One question @jefmoura Are we writing already tests or not? 😋

2019-02-04 13:58 UTC, docktorrr commented
@Menda Tests will follow, so do not merge it until tests are here. Just want to have the opinion on using JWT for invitation token.

2019-02-07 09:35 UTC, rafa-munoz commented on .flake8
> -exclude = settings,manage.py,wsgi.py,migrations,models
Why this is deleted?

2019-02-07 09:37 UTC, docktorrr commented on .flake8
> -exclude = settings,manage.py,wsgi.py,migrations,models
I put it in setup.cfg

2019-02-07 12:39 UTC, rafa-munoz commented on .flake8
> -exclude = settings,manage.py,wsgi.py,migrations,models
ahhh, ok

2019-02-11 10:50 UTC, jefmoura requested changes
There's a case that I didn't see being covered:
- When a user uses an invitation link, the token should be invalidated.

2019-02-11 10:50 UTC, jefmoura commented on bifrost-api/settings/base.py
> +REG_URL_PATH = os.getenv('REG_URL_PATH', 'register/')
It's better to type the whole name of it `REGISTRATION_URL_PATH`

2019-02-11 10:50 UTC, jefmoura commented on setup.cfg
> +testpaths=gateway/tests workflow/tests/test_jwt_utils.py workflow/tests/test_registration.py
Should we add the gateway folder as well?

2019-02-11 10:50 UTC, jefmoura commented on conftest.py
> +def req_factory():
I'd prefer to have the whole name `request_factory`

2019-02-11 10:50 UTC, jefmoura commented on workflow/models.py
> +            return '{} {}'.format(self.user.first_name,
As you're already updating the string, can you use f-string instead?

2019-02-11 10:50 UTC, jefmoura commented on workflow/models.py
> +            return "{} <{}>".format(self.name, self.organization.name)
As you're already updating the string, can you use f-string instead?

2019-02-11 10:50 UTC, jefmoura commented on workflow/models.py
> +        return "{} - {} <{}>".format(self.workflow_user, self.role,
As you're already updating the string, can you use f-string instead?

2019-02-11 10:50 UTC, jefmoura commented on workflow/serializers.py
> +        user_data['is_active'] = is_new_org or bool(invitation_token)
Are you checking if the `invitation_token` isn' empty? None? I'd prefer to do an explicit check instead of casting it to boolean.

2019-02-11 10:50 UTC, jefmoura commented on workflow/serializers.py
> +        return super(CoreUserSerializer, self).update(instance, validated_data)
Could you explain to me, why do we need to change the updated function? Because clients cannot see the user model inside of the core user model.
![firefox_screenshot_2019-02-11t10-36-06 471z](https://user-images.githubusercontent.com/4620451/52557947-3e790e80-2df1-11e9-8f6b-b5d6119d86da.png)

2019-02-11 10:50 UTC, jefmoura commented on workflow/tests/test_registration.py
> +        request = req_factory.post(reverse('coreuser-list'), data)
You should reverse `coreuser-create` instead

2019-02-11 10:50 UTC, jefmoura commented on workflow/tests/test_registration.py
> +    request = req_factory.put(reverse('coreuser-detail', args=(pk,)))
You should reverse `coreuser-update` instead

2019-02-11 10:50 UTC, jefmoura commented on workflow/tests/test_registration.py
> +    request = req_factory.post(reverse('coreuser-list'))
You should reverse `coreuser-create` instead

2019-02-11 10:50 UTC, jefmoura commented on workflow/tests/test_registration.py
> +    request = req_factory.patch(reverse('coreuser-detail', args=(1,)))
You should reverse `coreuser-partial-update` instead

2019-02-11 10:50 UTC, jefmoura commented on workflow/tests/test_registration.py
> +    request = req_factory.patch(reverse('coreuser-detail', args=(1,)))
You should reverse `coreuser-partial-update` instead

2019-02-11 10:50 UTC, jefmoura commented on workflow/tests/test_registration.py
> +    request = req_factory.put(reverse('coreuser-detail', args=(1,)))
You should reverse `coreuser-update` instead

2019-02-11 10:50 UTC, jefmoura commented on workflow/tests/test_registration.py
> +    request = req_factory.post(reverse('coreuser-list'), TEST_USER_DATA)
The same thing about the reverse above

2019-02-11 10:50 UTC, jefmoura commented on workflow/tests/test_registration.py
> +    request = req_factory.post(reverse('coreuser-list'), TEST_USER_DATA)
The same thing about the reverse the create URL

2019-02-11 10:50 UTC, jefmoura commented on workflow/tests/test_registration.py
> +    request = req_factory.post(reverse('coreuser-list'), data)
Again the create URL reverse

2019-02-11 10:50 UTC, jefmoura commented on workflow/tests/test_registration.py
> +    request = req_factory.patch(reverse('coreuser-detail', args=(pk,)), data)
The same thing about the reverse the partial update URL

2019-02-12 17:40 UTC, docktorrr commented on setup.cfg
> +testpaths=gateway/tests workflow/tests/test_jwt_utils.py workflow/tests/test_registration.py
But it is here :) Anyway I switched all the tests in refactoring branch

2019-02-12 17:48 UTC, docktorrr commented on workflow/serializers.py
> +        user_data['is_active'] = is_new_org or bool(invitation_token)
Try `False or None`, it will return None :-)

The second statement evaluated only if the first one is False

2019-02-12 18:09 UTC, docktorrr commented on workflow/serializers.py
> +        return super(CoreUserSerializer, self).update(instance, validated_data)
It's because of this error:
```
AssertionError: The .update() method does not support writable
nestedfields by default. Write an explicit .update() method for
serializer ..., or set
read_only=True on nested serializer fields.
```
https://github.com/encode/django-rest-framework/blob/dc6b3bf42e53c6bfdb597a67de931913c8bd0255/rest_framework/serializers.py#L827

2019-02-12 18:11 UTC, docktorrr commented on workflow/tests/test_registration.py
> +        request = req_factory.post(reverse('coreuser-list'), data)
coreuser-list is correct for POST (we already discussed today)

2019-02-12 18:11 UTC, docktorrr commented on workflow/tests/test_registration.py
> +    request = req_factory.put(reverse('coreuser-detail', args=(pk,)))
coreuser-detail is correct (we already discussed today)

2019-02-12 18:11 UTC, docktorrr commented on workflow/tests/test_registration.py
> +    request = req_factory.post(reverse('coreuser-list'))
see above

2019-02-12 18:12 UTC, docktorrr commented on workflow/tests/test_registration.py
> +    request = req_factory.patch(reverse('coreuser-detail', args=(1,)))
see above

2019-02-12 18:12 UTC, docktorrr commented on workflow/tests/test_registration.py
> +    request = req_factory.patch(reverse('coreuser-detail', args=(1,)))
see above

2019-02-12 18:12 UTC, docktorrr commented on workflow/tests/test_registration.py
> +    request = req_factory.put(reverse('coreuser-detail', args=(1,)))
see above

2019-02-12 18:12 UTC, docktorrr commented on workflow/tests/test_registration.py
> +    request = req_factory.post(reverse('coreuser-list'), TEST_USER_DATA)
see above

2019-02-12 18:12 UTC, docktorrr commented on workflow/tests/test_registration.py
> +    request = req_factory.post(reverse('coreuser-list'), TEST_USER_DATA)
see above

2019-02-12 18:12 UTC, docktorrr commented on workflow/tests/test_registration.py
> +    request = req_factory.post(reverse('coreuser-list'), data)
see above

2019-02-12 18:13 UTC, docktorrr commented on workflow/tests/test_registration.py
> +    request = req_factory.patch(reverse('coreuser-detail', args=(pk,)), data)
see above

2019-02-13 10:15 UTC, jefmoura commented on workflow/serializers.py
> +        return super(CoreUserSerializer, self).update(instance, validated_data)
I didn't know that. Thanks :smile:

2019-02-13 10:16 UTC, jefmoura commented on workflow/tests/test_registration.py
> +        request = req_factory.post(reverse('coreuser-list'), data)
Yes. I remember.
Info about it: https://www.django-rest-framework.org/api-guide/routers/#simplerouter

2019-02-13 10:16 UTC, jefmoura commented on workflow/tests/test_registration.py
> +    request = req_factory.put(reverse('coreuser-detail', args=(pk,)))
Yes. I remember.
Info about it: https://www.django-rest-framework.org/api-guide/routers/#simplerouter

2019-02-13 10:17 UTC, jefmoura commented
@docktorrr tests are failing. Check it out! http://drone.humanitec.io/Humanitec/bifrost/477/4

2019-02-13 10:19 UTC, docktorrr commented on bifrost-api/settings/base.py
> +REG_URL_PATH = os.getenv('REG_URL_PATH', 'register/')
done

2019-02-13 10:19 UTC, docktorrr commented on conftest.py
> +def req_factory():
done

2019-02-13 10:19 UTC, docktorrr commented on workflow/models.py
> +            return '{} {}'.format(self.user.first_name,
done

2019-02-13 10:19 UTC, jefmoura commented
@paraghumanitec @docktorrr As we talked about invalidating a token, we need to create a ticket for it.

2019-02-13 10:19 UTC, docktorrr commented on workflow/models.py
> +            return "{} <{}>".format(self.name, self.organization.name)
done

2019-02-13 10:19 UTC, docktorrr commented on workflow/models.py
> +        return "{} - {} <{}>".format(self.workflow_user, self.role,
done

2019-02-13 10:22 UTC, docktorrr commented
@jefmoura already made a fix to pass the test, in the last commit

2019-02-13 10:29 UTC, jefmoura submitted a review, later dismissed

2019-02-13 10:37 UTC, ybekdemir commented
Use rebase instead for the "Merge branch 'master' into add-registration-proce"

2019-02-13 10:40 UTC, jefmoura approved these changes

2019-02-13 10:40 UTC, merged