Ignore case sensitivity in aggregate query argument
buildlyio/buildly-core pull request #32
Opened 2019-02-14 09:41 UTC by ralfzen

I think it improves the usability of our data mesh.

2019-02-14 17:26 UTC, jefmoura submitted a review, later dismissed

2019-02-14 17:26 UTC, jefmoura commented
You need to rebase @ralfzen

2019-02-15 08:32 UTC, jefmoura requested changes
There's no test

2019-02-18 11:19 UTC, ralfzen commented
Hi @jefmoura,
I rebased this one and adapted a test, which now covers the new functionality.

2019-02-18 11:25 UTC, jefmoura approved these changes

2019-02-18 11:25 UTC, merged