EndpointNotFoundException w/ path and METHOD
buildlyio/buildly-core pull request #51
Opened 2019-03-04 16:54 UTC by ralfzen

## Purpose
GET on `/messaging/email/` returned an AttributeError because there is only a POST.

## Approach
To understand faster, what was wrong I added the EndpointNotFoundException here.

2019-03-04 17:02 UTC, docktorrr requested changes

2019-03-04 17:02 UTC, docktorrr commented on gateway/views.py
> +            if not getattr(path_item, method):
I guess you should use here `hasattr()` otherwise AttributeError could be raised.

2019-03-04 17:11 UTC, ralfzen commented on gateway/views.py
> +            if not getattr(path_item, method):
`getattr` will just return `None`. So that works, but you're right: `hasattr` is nicer, so I'll change it

2019-03-04 17:13 UTC, docktorrr commented on gateway/views.py
> +            if not getattr(path_item, method):
> getattr(object, name[, default])

> If the named attribute does not exist, default is returned if provided, otherwise AttributeError is raised.

2019-03-04 17:14 UTC, ralfzen commented on gateway/views.py
> +            if not getattr(path_item, method):
I tested it, `hasattr` doesn't work.

2019-03-04 21:06 UTC, jefmoura reviewed
Why `EndpointNotFound` will be 500 and not 404 anymore?

2019-03-04 21:06 UTC, jefmoura commented on gateway/exceptions.py
> +            msg = f'Endpoint not found: {msg}'
Will this be the error message `Endpoint not found: Endpoint not found` if we use the default? Better to be required so.

2019-03-04 21:06 UTC, jefmoura commented on gateway/exceptions.py
> +    def __init__(self, msg, status: int = 500):
Why all exceptions raised by thegatway are 500 now?

2019-03-05 08:29 UTC, ralfzen commented on gateway/exceptions.py
> +    def __init__(self, msg, status: int = 500):
Here I just wanted to pass a `default` - value, so for the case, if no status is given. With `None` it would always raise an error, because it must be an Integer value.
@docktorrr just proposed `400` instead.

2019-03-05 10:37 UTC, ralfzen commented
reworked

2019-03-05 10:56 UTC, docktorrr submitted a review, later dismissed

2019-03-06 15:37 UTC, jefmoura commented
You need to rebase it @ralfzen

2019-03-06 15:44 UTC, ralfzen commented
@jefmoura I wanted to add tests before I rebase.

2019-03-08 10:25 UTC, jefmoura commented on gateway/tests/test_views.py
> +        mock_app.return_value = app
You can use `side_effect`.
Like we do here: https://github.com/Humanitec/bifrost/blob/master/gateway/tests/test_data_mesh.py#L644

2019-03-08 10:25 UTC, jefmoura commented on gateway/tests/test_views.py
> +        app.s = lambda l: None
Do you really need to add a lambda function to the `app.s`?
This line means that `path_item` in `_get_req_and_rep` will be `None`

2019-03-08 10:37 UTC, jefmoura approved these changes

2019-03-08 10:42 UTC, merged