PLAT-165: refactor permission classes
buildlyio/buildly-core pull request #84
Opened 2019-04-02 16:10 UTC by docktorrr

## Purpose
Replace old WorkflowTeam-based permission class with  CoreGroup-based permission class

## Approach
1) Add CoreGroup fields `is_global`, `is_org_level` and `organization`
2) `AllowCoreUserRoles` rename to `CoreGroupsPermissions`
3) Change it according to CoreGroups
4) Replace name-based permission constants with the integer-based.

### Further Info
@jefmoura  I have to write/fix tests. Please don't merge, just comment if you have any feedback.

2019-04-05 08:03 UTC, jefmoura commented
The build is failing. Please, check it @docktorrr

2019-04-05 08:05 UTC, docktorrr commented
Yes, because of tests, I mentioned it. Tests are coming. Just wanted to have some feedback on permission class code.

2019-04-05 09:40 UTC, jefmoura requested changes

2019-04-05 09:40 UTC, jefmoura commented on workflow/permissions.py
> +                global_permissions = merge_permissions(global_permissions, group.display_permissions)
You're merging the permissions in both cases if it's global or org level. Why don't you put them in only one conditional?

2019-04-05 09:40 UTC, jefmoura commented on workflow/permissions.py
> +                for wl2 in group.workflowlevel1s.all():
Shouldn't it be `workflowlevel2s`?

2019-04-05 09:40 UTC, jefmoura commented on workflow/permissions.py
> +                for wl1 in group.workflowlevel1s.all():
I think it would be better to get the workflowlevel1/2 permissions when it's needed

2019-04-05 09:40 UTC, jefmoura commented on workflow/permissions.py
> +        if request.user.is_org_admin():
and if it's global?

2019-04-08 11:51 UTC, docktorrr commented on workflow/permissions.py
> +                global_permissions = merge_permissions(global_permissions, group.display_permissions)
It is a mistake - I need to merge `org_permissions` instead of `global_permissions` in the second case. I'll fix it.

2019-04-08 11:54 UTC, docktorrr commented on workflow/permissions.py
> +                for wl2 in group.workflowlevel1s.all():
Of course, I'll fix it.

2019-04-08 12:24 UTC, docktorrr commented on workflow/permissions.py
> +        if request.user.is_org_admin():
Yes, there's some incorrect logic here, we also need to check that the user and the object belong to the same organization. I'll update it.

2019-04-10 13:56 UTC, docktorrr commented
@jefmoura Now all tests are passed, you can check it

2019-04-15 09:07 UTC, jefmoura commented on bifrost-api/management/commands/loadinitialdata.py
> +        CoreGroup.objects.filter(is_global=True).delete()
I'm not sure if it's a good idea to delete the group because this will be triggered all the time when we restart a container and users will lose their relationship with the group.

2019-04-15 09:07 UTC, jefmoura commented on workflow/models.py
> +        Check if user has organization level admin permissions
Don't need to change, but why this function isn't a `property`, like `is_superuser` and `is_active`?

2019-04-15 09:07 UTC, jefmoura commented on workflow/models.py
> +    def is_global_admin(self) -> bool:
This one could also be a `property`, so it's easier to use

2019-04-15 09:07 UTC, jefmoura commented on workflow/permissions.py
> +def has_permission(permissions_: str, action: str) -> bool:
why do we have this underscore in the name of the var?

2019-04-15 09:07 UTC, jefmoura commented on workflow/permissions.py
> +        global_permissions, org_permissions = '0100', '0100'
I think it should be allowed to read. Why don't you use the constant that you've created `PERMISSIONS_VIEW_ONLY`?

2019-04-15 09:07 UTC, jefmoura commented on workflow/permissions.py
> +        if hasattr(obj, 'organization') and not request.user.organization == obj.organization:
If somebody decides to have cross-org objects, it's not gonna be possible with this permission class, that's why we had another class just to validate organizations.

2019-04-15 09:07 UTC, jefmoura commented on workflow/signals.py
> +        defaults={'name': 'Organization Admin', 'permissions': PERMISSIONS_ORG_ADMIN}
Maybe you forgot to replace `'Organization Admin'` to the real org name

2019-04-15 09:07 UTC, jefmoura commented on workflow/views.py
> +        queryset = queryset.filter(organization_id=request.user.organization_id)
Super users should be able to see all workflow levels even if they don't belong to their organization, shouldn't they?

2019-04-15 09:07 UTC, jefmoura commented on workflow/views.py
> +            queryset = queryset.filter(workflowlevel1__organization_id=organization_id)
Super users should be able to see all workflow levels even if they don't belong to their organization, shouldn't they?

2019-04-15 09:15 UTC, docktorrr commented on workflow/models.py
> +        Check if user has organization level admin permissions
It's not a big deal in my opinion, but I'll change it.

2019-04-15 09:15 UTC, docktorrr commented on workflow/models.py
> +    def is_global_admin(self) -> bool:
The same as above

2019-04-15 09:20 UTC, docktorrr commented on workflow/permissions.py
> +def has_permission(permissions_: str, action: str) -> bool:
Because it shadows name from outer context:
`from rest_framework import permissions`. It's a common practice to avoid the conflicts (see https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles)

2019-04-15 09:26 UTC, docktorrr commented on workflow/signals.py
> +        defaults={'name': 'Organization Admin', 'permissions': PERMISSIONS_ORG_ADMIN}
No. We have organization field, so we can derive org name from it. Anyway it's just information field, we can give any name we like. If you think we should add org name to it, I'll add it, but I think it's not ver y important at this moment.

2019-04-15 09:32 UTC, docktorrr commented on workflow/views.py
> +        queryset = queryset.filter(organization_id=request.user.organization_id)
Of course they should, probably it's a mistake, I'll double check the logic.

2019-04-15 15:54 UTC, docktorrr commented on bifrost-api/management/commands/loadinitialdata.py
> +        CoreGroup.objects.filter(is_global=True).delete()
Agree, but we also should change other things in this script as the CoreUser deleting and creating, updating oauth application etc.

2019-04-15 16:42 UTC, docktorrr commented on bifrost-api/management/commands/loadinitialdata.py
> +        CoreGroup.objects.filter(is_global=True).delete()
Fix it, and superuser as well

2019-04-16 12:22 UTC, docktorrr commented
@jefmoura fixes are done

2019-04-18 09:51 UTC, jefmoura commented on workflow/permissions.py
> +def has_permission(permissions_: str, action: str) -> bool:
ok... didn't know that. Thanks for the link.

> single_trailing_underscore_: used by convention to avoid conflicts with Python keyword

2019-04-18 10:03 UTC, jefmoura approved these changes

2019-04-18 10:03 UTC, merged